version: "3"

services:
  remotenv:
    image: remotenv/application
    restart: unless-stopped
    environment:
      ACCESS_TOKEN: "12345"
    ports:
      - 3420:3420
    volumes:
      - remotenv:/data/remotenv

volumes:
  remotenv:
